apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- https://github.com/cert-manager/cert-manager/releases/download/v1.11.0/cert-manager.yaml
#- overlay/cert-manager-config.yaml
- base

# #NGINX helm chart
# helmChartInflationGenerator:
# - chartName: ingress-nginx
#   chartRepoUrl: https://github.com/kubernetes/ingress-nginx
#   chartVersion: 4.6.0
#   releaseName: ingress-nginx
#   releaseNamespace: ingress
#   # override with these custom values
#   values: overlay/values.yaml

helmCharts:
- name: ingress-nginx
  namespace: ingress
  includeCRDs: false
  valuesInline:
    controller:
      replicaCount: 2
      service:
        enabled: true
        annotations: {service.beta.kubernetes.io/azure-load-balancer-health-probe-request-path: healthz}
  releaseName: ingress-nginx
  version: 4.6.0
  repo: https://kubernetes.github.io/ingress-nginx