apiVersion: v1
data:
  oidc.config: |
    name: Azure
    issuer: https://login.microsoftonline.com/703922c4-f042-4683-9e67-a969c8abc975/v2.0
    clientID: $oidc-azure-clientId
    clientSecret: $oidc-azure-clientSecret
    requestedScopes:
       - openid
       - email
  url: https://argocdyy.crabdance.com/
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-cm
  # namespace: argocd