apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    # staging environment
    server: https://acme-staging-v02.api.letsencrypt.org/directory #use https://acme-v02.api.letsencrypt.org/directory for production
    email: yaroslav@datainsights.de
    privateKeySecretRef:
      name: letsencrypt
    solvers:
    - http01:
        ingress:
          class: nginx
          podTemplate:
            spec:
              nodeSelector:
                "kubernetes.io/os": linux