apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - argocd-namespace.yaml
  - https://raw.githubusercontent.com/argoproj/argo-cd/master/manifests/install.yaml
  - cert-manager-config.yaml
  - ingress-rule.yaml

components:
  - https://github.com/argoproj-labs/argocd-extensions/manifests
